---
resource_types:

- name: kubernetes
  type: docker-image
  source:
    repository: virtmerlin/concourse-kubernetes-resource

- name: harbor-image
  privileged: true
  type: docker-image
  source:
    repository: virtmerlin/harbor-image-resource
    tag: latest

resources:

- name: git-go-http
  type: git
  source:
    uri: https://github.com/tkrausjr/go-http
    branch: master

- name: harbor
  type: harbor-image
  source:
    username: ((harbor_username))
    password: ((harbor_password))
    skip_pull: true
    repository: ((harbor_host))/((harbor_image))
    insecure_registries:
    - ((harbor_host))
    harbor_host: ((harbor_host))
    harbor_image: ((harbor_image))
    harbor_trigger_scan: ((harbor_trigger_scan))
    harbor_scan_thresholds: ((harbor_scan_thresholds))
    notary_enable: ((notary_enable))
    notary_url: ((notary_url))
    notary_vault_addr: ((notary_vault_addr))
    notary_vault_token: ((notary_vault_token))

jobs:

- name: build-docker-image
  plan:
  - get: git-go-http
    trigger: true
  - put: harbor
    params: {build: git-go-http}

