---
resource_types:

- name: kubernetes
  type: docker-image
  source:
    repository: virtmerlin/concourse-kubernetes-resource

resources:

- name: git-go-http
  type: git
  source:
    uri: https://github.com/tkrausjr/go-http
    branch: master

- name: harbor-image
  type: docker-image
  source:
    username: ((harbor_username))
    password: ((harbor_password))
    repository: ((harbor_url))/((harbor_image))
    insecure_registries:
    - ((harbor_url))

jobs:
- name: build-docker-image
  plan:
  - aggregate:
    - get: git-go-http
    - put: harbor-image
      params: {build: go-http}
