---
resource_types:

- name: kubernetes
  type: docker-image
  source:
    repository: virtmerlin/concourse-kubernetes-resource

- name: harbor-image
  privileged: true
  type: docker-image
  source:
    repository: virtmerlin/harbor-image-resource

resources:

- name: secure-docker-image-build-ci
  type: git
  source:
    uri: https://github.com/virtmerlin/secure-docker-image-build-ci
    branch: master

- name: git-go-http
  type: git
  source:
    uri: https://github.com/tkrausjr/go-http
    branch: master

- name: harbor
  type: harbor-image
  source:
    username: ((harbor_username))
    password: ((harbor_password))
    skip_pull: true
    repository: ((harbor_host))/((harbor_image))
    insecure_registries:
    - ((harbor_url))
    notary_enable: ((notary_enable))
    notary_url: ((notary_url))
    notary_vault_addr: ((notary_vault_addr))
    notary_vault_token: ((notary_vault_token))

jobs:

- name: build-docker-image
  plan:
  - get: secure-docker-image-build-ci
  - get: git-go-http
    trigger: true
  - put: harbor
    params: {build: git-go-http}

- name: cve-report-harbor-image
  plan:
  - get: secure-docker-image-build-ci
    passed: [build-docker-image]
    trigger: true
  - task: clair-cve-report
    file: secure-docker-image-build-ci/tasks/cve-report-harbor-image/task.yml
    params:
      harbor_username: ((harbor_username))
      harbor_password: ((harbor_password))
      harbor_host: ((harbor_host))
      harbor_repository: ((harbor_image))
      harbor_trigger_scan: ((harbor_trigger_scan))
      harbor_scan_thresholds: ((harbor_scan_thresholds))
