---

platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu}

params:

inputs:
  - name: git-spring1-ci
  - name: git-go-http

run:
  path: git-spring1-ci/tasks/debug/task.sh
